import type { Product } from "./types";

const tenisBranco = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=2070&auto=format&fit=crop";
const tenisPreto = "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1999&auto=format&fit=crop";
const scarpin = "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=2080&auto=format&fit=crop";
const sandalia = "https://images.unsplash.com/photo-1562273103-91206b77af11?q=80&w=1964&auto=format&fit=crop";
const bota = "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?q=80&w=1974&auto=format&fit=crop";
const mocassim = "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?q=80&w=1930&auto=format&fit=crop";

const SIZES_FEM = ["34", "35", "36", "37", "38", "39"];
const SIZES_MASC = ["38", "39", "40", "41", "42", "43"];

const CHART_FEM = [
  { size: "34", equivalence: "22,0 cm" },
  { size: "35", equivalence: "22,8 cm" },
  { size: "36", equivalence: "23,5 cm" },
  { size: "37", equivalence: "24,3 cm" },
  { size: "38", equivalence: "25,0 cm" },
  { size: "39", equivalence: "25,8 cm" },
];

const CHART_MASC = [
  { size: "38", equivalence: "24,8 cm" },
  { size: "39", equivalence: "25,5 cm" },
  { size: "40", equivalence: "26,2 cm" },
  { size: "41", equivalence: "27,0 cm" },
  { size: "42", equivalence: "27,7 cm" },
  { size: "43", equivalence: "28,5 cm" },
];

type Seed = Omit<Product, "price" | "product_id"> & { product_id?: number };

const seeds: Seed[] = [
  {
    name: "Tênis Adidas Runfalcon 3.0",
    slug: "tenis-adidas-runfalcon-3-0",
    sku: "INV-CAL-0101",
    brand: "Adidas",
    short_description: "Tênis esportivo leve com amortecimento para o dia a dia.",
    description:
      "O Runfalcon 3.0 combina cabedal em tecido respirável e entressola macia para quem passa o dia em movimento. Acabamento limpo em branco total, fácil de compor com jeans, alfaiataria leve ou look esportivo.",
    images: [{ src: tenisBranco, alt: "Tênis Adidas Runfalcon branco visto de três quartos" }],
    categories: ["calcados"],
    gender: "unissex",
    regular_price: 449.9,
    sale_price: 399.9,
    sizes: SIZES_MASC,
    colors: ["Branco"],
    stock_status: "instock",
    stock_quantity: 18,
    rating: 4.8,
    rating_count: 46,
    featured: true,
    is_new: true,
    best_seller: 96,
    created_at: "2026-07-28",
    attributes: [
      { label: "Material", value: "Têxtil e sintético" },
      { label: "Solado", value: "EVA com borracha" },
      { label: "Palmilha", value: "Removível acolchoada" },
    ],
    size_chart: CHART_MASC,
    reviews: [
      {
        author: "Rafaela M.",
        rating: 5,
        date: "2026-07-02",
        comment: "Muito confortável e chegou rápido. Comprei pelo WhatsApp e fui bem atendida.",
      },
    ],
  },
  {
    name: "Tênis Puma Softride Preto",
    slug: "tenis-puma-softride-preto",
    sku: "INV-CAL-0102",
    brand: "Puma",
    short_description: "Silhueta esportiva all black com pisada macia.",
    description:
      "Versão monocromática do Softride, com espuma de retorno suave e cabedal em malha. Discreto o suficiente para o ambiente de trabalho e confortável para as caminhadas do fim de semana.",
    images: [{ src: tenisPreto, alt: "Tênis Puma Softride preto de perfil" }],
    categories: ["calcados"],
    gender: "masculino",
    regular_price: 379.9,
    sale_price: null,
    sizes: SIZES_MASC,
    colors: ["Preto"],
    stock_status: "instock",
    stock_quantity: 12,
    rating: 4.6,
    rating_count: 31,
    featured: true,
    is_new: false,
    best_seller: 88,
    created_at: "2026-06-11",
    attributes: [
      { label: "Material", value: "Malha respirável" },
      { label: "Solado", value: "Softride" },
    ],
    size_chart: CHART_MASC,
    reviews: [],
  },
  {
    name: "Scarpin Vizzano Bico Fino Nude",
    slug: "scarpin-vizzano-bico-fino-nude",
    sku: "INV-CAL-0103",
    brand: "Vizzano",
    short_description: "Scarpin clássico em verniz, salto fino de 9 cm.",
    description:
      "O scarpin nude alonga a silhueta e resolve do escritório ao casamento. Verniz de brilho uniforme, forro macio e palmilha almofadada para uso prolongado.",
    images: [{ src: scarpin, alt: "Scarpin Vizzano nude de bico fino" }],
    categories: ["calcados"],
    gender: "feminino",
    regular_price: 219.9,
    sale_price: 179.9,
    sizes: SIZES_FEM,
    colors: ["Nude"],
    stock_status: "instock",
    stock_quantity: 22,
    rating: 4.7,
    rating_count: 58,
    featured: true,
    is_new: false,
    best_seller: 94,
    created_at: "2026-05-20",
    attributes: [
      { label: "Altura do salto", value: "9 cm" },
      { label: "Material", value: "Verniz sintético" },
    ],
    size_chart: CHART_FEM,
    reviews: [],
  },
  {
    name: "Sandália Moleca Tiras Caramelo",
    slug: "sandalia-moleca-tiras-caramelo",
    sku: "INV-CAL-0104",
    brand: "Moleca",
    short_description: "Rasteira de tiras finas com fecho no tornozelo.",
    description:
      "Rasteira leve de tiras em caramelo, com fivela metálica e palmilha anatômica. A peça mais versátil do verão: combina com vestido, short e alfaiataria clara.",
    images: [{ src: sandalia, alt: "Sandália rasteira Moleca caramelo com tiras" }],
    categories: ["calcados"],
    gender: "feminino",
    regular_price: 149.9,
    sale_price: 119.9,
    sizes: SIZES_FEM,
    colors: ["Caramelo"],
    stock_status: "instock",
    stock_quantity: 30,
    rating: 4.5,
    rating_count: 24,
    featured: false,
    is_new: true,
    best_seller: 72,
    created_at: "2026-08-01",
    attributes: [
      { label: "Fechamento", value: "Fivela" },
      { label: "Palmilha", value: "Anatômica" },
    ],
    size_chart: CHART_FEM,
    reviews: [],
  },
  {
    name: "Bota Ramarim Cano Curto",
    slug: "bota-ramarim-cano-curto",
    sku: "INV-CAL-0105",
    brand: "Ramarim",
    short_description: "Ankle boot em couro sintético com salto bloco.",
    description:
      "Cano curto, zíper lateral e salto bloco de 4 cm: a bota que atravessa o ano. Caimento estruturado que valoriza calça reta e vestido midi.",
    images: [{ src: bota, alt: "Ankle boot Ramarim marrom de cano curto" }],
    categories: ["calcados"],
    gender: "feminino",
    regular_price: 299.9,
    sale_price: null,
    sizes: SIZES_FEM,
    colors: ["Marrom"],
    stock_status: "instock",
    stock_quantity: 9,
    rating: 4.4,
    rating_count: 17,
    featured: false,
    is_new: false,
    best_seller: 61,
    created_at: "2026-04-14",
    attributes: [
      { label: "Altura do salto", value: "4 cm" },
      { label: "Fechamento", value: "Zíper lateral" },
    ],
    size_chart: CHART_FEM,
    reviews: [],
  },
  {
    name: "Mocassim Ferracini Couro Whisky",
    slug: "mocassim-ferracini-couro-whisky",
    sku: "INV-CAL-0106",
    brand: "Ferracini",
    short_description: "Mocassim social em couro legítimo, solado costurado.",
    description:
      "Construção em couro legítimo com acabamento whisky e costura aparente. Peça de base para o guarda-roupa masculino, do trabalho ao casamento.",
    images: [{ src: mocassim, alt: "Mocassim masculino em couro whisky" }],
    categories: ["calcados"],
    gender: "masculino",
    regular_price: 429.9,
    sale_price: 369.9,
    sizes: SIZES_MASC,
    colors: ["Whisky"],
    stock_status: "instock",
    stock_quantity: 7,
    rating: 4.9,
    rating_count: 22,
    featured: true,
    is_new: false,
    best_seller: 84,
    created_at: "2026-03-22",
    attributes: [
      { label: "Material", value: "Couro legítimo" },
      { label: "Solado", value: "Costurado" },
    ],
    size_chart: CHART_MASC,
    reviews: [],
  },
  {
    name: "Tênis Olympikus Corre 3",
    slug: "tenis-olympikus-corre-3",
    sku: "INV-CAL-0107",
    brand: "Olympikus",
    short_description: "Tênis de corrida nacional, leve e respirável.",
    description:
      "Desenvolvido para rodagem diária, com entressola responsiva e cabedal em knit. Excelente relação entre conforto e preço para quem começa a correr.",
    images: [{ src: tenisBranco, alt: "Tênis de corrida Olympikus branco" }],
    categories: ["calcados"],
    gender: "unissex",
    regular_price: 329.9,
    sale_price: 279.9,
    sizes: SIZES_MASC,
    colors: ["Branco"],
    stock_status: "instock",
    stock_quantity: 14,
    rating: 4.5,
    rating_count: 39,
    featured: false,
    is_new: false,
    best_seller: 78,
    created_at: "2026-02-19",
    attributes: [{ label: "Indicação", value: "Corrida e caminhada" }],
    size_chart: CHART_MASC,
    reviews: [],
  },
  {
    name: "Sapatilha Beira Rio Bico Redondo",
    slug: "sapatilha-beira-rio-bico-redondo",
    sku: "INV-CAL-0108",
    brand: "Beira Rio",
    short_description: "Sapatilha confortável para uso diário.",
    description:
      "Modelo fechado de bico redondo, com elástico discreto no cós e palmilha macia. Alternativa prática ao salto sem perder a elegância.",
    images: [{ src: scarpin, alt: "Sapatilha feminina Beira Rio nude" }],
    categories: ["calcados"],
    gender: "feminino",
    regular_price: 139.9,
    sale_price: null,
    sizes: SIZES_FEM,
    colors: ["Nude"],
    stock_status: "outofstock",
    stock_quantity: 0,
    rating: 4.3,
    rating_count: 12,
    featured: false,
    is_new: false,
    best_seller: 55,
    created_at: "2026-01-30",
    attributes: [{ label: "Material", value: "Sintético" }],
    size_chart: CHART_FEM,
    reviews: [],
  },
  {
    name: "Tênis Mizuno Wave Feminino",
    slug: "tenis-mizuno-wave-feminino",
    sku: "INV-CAL-0109",
    brand: "Mizuno",
    short_description: "Tênis de performance com tecnologia de amortecimento.",
    description:
      "Placa Wave para distribuição do impacto, cabedal em mesh e ajuste preciso no calcanhar. Indicado para treinos de rua e academia.",
    images: [{ src: tenisBranco, alt: "Tênis Mizuno Wave feminino branco" }],
    categories: ["calcados"],
    gender: "feminino",
    regular_price: 599.9,
    sale_price: 499.9,
    sizes: SIZES_FEM,
    colors: ["Branco"],
    stock_status: "instock",
    stock_quantity: 5,
    rating: 4.9,
    rating_count: 20,
    featured: true,
    is_new: true,
    best_seller: 91,
    created_at: "2026-08-10",
    attributes: [{ label: "Indicação", value: "Treino e corrida" }],
    size_chart: CHART_FEM,
    reviews: [],
  },
  {
    name: "Sandália Salto Bloco Vizzano",
    slug: "sandalia-salto-bloco-vizzano",
    sku: "INV-CAL-0110",
    brand: "Vizzano",
    short_description: "Sandália elegante com salto bloco médio.",
    description: "Ideal para eventos e trabalho, proporcionando conforto e estilo.",
    images: [{ src: sandalia, alt: "Sandália Vizzano salto bloco" }],
    categories: ["calcados"],
    gender: "feminino",
    regular_price: 189.9,
    sale_price: 159.9,
    sizes: SIZES_FEM,
    colors: ["Preto"],
    stock_status: "instock",
    stock_quantity: 15,
    rating: 4.8,
    rating_count: 15,
    featured: true,
    is_new: true,
    best_seller: 85,
    created_at: "2026-08-12",
    attributes: [{ label: "Salto", value: "5 cm" }],
    size_chart: CHART_FEM,
    reviews: [],
  },
  {
    name: "Bota Coturno Via Marte",
    slug: "bota-coturno-via-marte",
    sku: "INV-CAL-0111",
    brand: "Via Marte",
    short_description: "Coturno tratorado com acabamento premium.",
    description: "Estilo urbano e resistente para os dias mais frios.",
    images: [{ src: bota, alt: "Bota coturno Via Marte" }],
    categories: ["calcados"],
    gender: "feminino",
    regular_price: 349.9,
    sale_price: null,
    sizes: SIZES_FEM,
    colors: ["Preto"],
    stock_status: "instock",
    stock_quantity: 10,
    rating: 4.7,
    rating_count: 12,
    featured: false,
    is_new: true,
    best_seller: 70,
    created_at: "2026-08-11",
    attributes: [{ label: "Solado", value: "Tratorado" }],
    size_chart: CHART_FEM,
    reviews: [],
  }
];

export const MOCK_PRODUCTS: Product[] = seeds.map((seed, index) => ({
  ...seed,
  product_id: 1000 + index,
  price: seed.sale_price ?? seed.regular_price,
}));
