import type { Product } from "./types";

const tenisBranco = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=2070&auto=format&fit=crop";
const tenisPreto = "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1999&auto=format&fit=crop";
const scarpin = "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=2080&auto=format&fit=crop";
const sandalia = "https://images.unsplash.com/photo-1562273103-91206b77af11?q=80&w=1964&auto=format&fit=crop";
const bota = "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?q=80&w=1974&auto=format&fit=crop";
const mocassim = "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?q=80&w=1930&auto=format&fit=crop";

const SIZES_FEM = ["34", "35", "36", "37", "38", "39"];
const SIZES_MASC = ["38", "39", "40", "41", "42", "43"];

const CHART_FEM = [
  { size: "34", equivalence: "22,0 cm" },
  { size: "35", equivalence: "22,8 cm" },
  { size: "36", equivalence: "23,5 cm" },
  { size: "37", equivalence: "24,3 cm" },
  { size: "38", equivalence: "25,0 cm" },
  { size: "39", equivalence: "25,8 cm" },
];

const CHART_MASC = [
  { size: "38", equivalence: "24,8 cm" },
  { size: "39", equivalence: "25,5 cm" },
  { size: "40", equivalence: "26,2 cm" },
  { size: "41", equivalence: "27,0 cm" },
  { size: "42", equivalence: "27,7 cm" },
  { size: "43", equivalence: "28,5 cm" },
];

type Seed = Omit<Product, "price" | "product_id"> & { product_id?: number };

const seeds: Seed[] = [
  {
    name: "Tênis Adidas Runfalcon 3.0",
    slug: "tenis-adidas-runfalcon-3-0",
    sku: "INV-CAL-0101",
    brand: "Adidas",
    short_description: "Tênis esportivo leve com amortecimento para o dia a dia.",
    description:
      "O Runfalcon 3.0 combina cabedal em tecido respirável e entressola macia para quem passa o dia em movimento.",
    images: [{ src: tenisBranco, alt: "Tênis Adidas Runfalcon branco" }],
    categories: ["calcados", "masculino"],
    gender: "unissex",
    regular_price: 449.9,
    sale_price: 399.9,
    sizes: SIZES_MASC,
    colors: ["Branco"],
    stock_status: "instock",
    stock_quantity: 18,
    rating: 4.8,
    rating_count: 46,
    featured: true,
    is_new: true,
    best_seller: 96,
    created_at: "2026-07-28",
    attributes: [
      { label: "Material", value: "Têxtil e sintético" },
      { label: "Solado", value: "EVA com borracha" },
    ],
    size_chart: CHART_MASC,
    reviews: [],
  },
  {
    name: "Tênis Puma Softride Preto",
    slug: "tenis-puma-softride-preto",
    sku: "INV-CAL-0102",
    brand: "Puma",
    short_description: "Silhueta esportiva all black com pisada macia.",
    description:
      "Versão monocromática do Softride, com espuma de retorno suave e cabedal em malha.",
    images: [{ src: tenisPreto, alt: "Tênis Puma Softride preto" }],
    categories: ["calcados", "masculino"],
    gender: "masculino",
    regular_price: 379.9,
    sale_price: null,
    sizes: SIZES_MASC,
    colors: ["Preto"],
    stock_status: "instock",
    stock_quantity: 12,
    rating: 4.6,
    rating_count: 31,
    featured: true,
    is_new: false,
    best_seller: 88,
    created_at: "2026-06-11",
    attributes: [
      { label: "Material", value: "Malha respirável" },
      { label: "Solado", value: "Softride" },
    ],
    size_chart: CHART_MASC,
    reviews: [],
  },
  {
    name: "Scarpin Vizzano Bico Fino Nude",
    slug: "scarpin-vizzano-bico-fino-nude",
    sku: "INV-CAL-0103",
    brand: "Vizzano",
    short_description: "Scarpin clássico em verniz, salto fino de 9 cm.",
    description:
      "O scarpin nude alonga a silhueta e resolve do escritório ao casamento.",
    images: [{ src: scarpin, alt: "Scarpin Vizzano nude" }],
    categories: ["calcados", "feminino"],
    gender: "feminino",
    regular_price: 219.9,
    sale_price: 179.9,
    sizes: SIZES_FEM,
    colors: ["Nude"],
    stock_status: "instock",
    stock_quantity: 22,
    rating: 4.7,
    rating_count: 58,
    featured: true,
    is_new: false,
    best_seller: 94,
    created_at: "2026-05-20",
    attributes: [
      { label: "Altura do salto", value: "9 cm" },
      { label: "Material", value: "Verniz sintético" },
    ],
    size_chart: CHART_FEM,
    reviews: [],
  },
  {
    name: "Sandália Moleca Tiras Caramelo",
    slug: "sandalia-moleca-tiras-caramelo",
    sku: "INV-CAL-0104",
    brand: "Moleca",
    short_description: "Rasteira de tiras finas com fecho no tornozelo.",
    description: "Rasteira leve de tiras em caramelo, com fivela metálica e palmilha anatômica.",
    images: [{ src: sandalia, alt: "Sandália Moleca caramelo" }],
    categories: ["calcados", "feminino"],
    gender: "feminino",
    regular_price: 149.9,
    sale_price: 119.9,
    sizes: SIZES_FEM,
    colors: ["Caramelo"],
    stock_status: "instock",
    stock_quantity: 30,
    rating: 4.5,
    rating_count: 24,
    featured: false,
    is_new: true,
    best_seller: 72,
    created_at: "2026-08-01",
    attributes: [{ label: "Fechamento", value: "Fivela" }],
    size_chart: CHART_FEM,
    reviews: [],
  },
  {
    name: "Tênis Infantil Bibi Roller",
    slug: "tenis-infantil-bibi-roller",
    sku: "INV-CAL-0112",
    brand: "Bibi",
    short_description: "Tênis infantil fácil de calçar.",
    description: "Conforto e segurança para as crianças brincarem o dia todo.",
    images: [{ src: tenisBranco, alt: "Tênis infantil Bibi" }],
    categories: ["calcados", "infantil"],
    gender: "unissex",
    regular_price: 199.9,
    sale_price: 169.9,
    sizes: ["25", "26", "27", "28", "29", "30"],
    colors: ["Azul"],
    stock_status: "instock",
    stock_quantity: 25,
    rating: 4.9,
    rating_count: 15,
    featured: true,
    is_new: true,
    best_seller: 80,
    created_at: "2026-08-10",
    attributes: [{ label: "Tipo", value: "Slip-on" }],
    size_chart: [{ size: "25", equivalence: "16,5 cm" }],
    reviews: [],
  },
  {
    name: "Sandália Infantil Grendene Kids",
    slug: "sandalia-infantil-grendene-kids",
    sku: "INV-CAL-0113",
    brand: "Grendene",
    short_description: "Sandália infantil temática e divertida.",
    description: "Leveza e diversão para o dia a dia das crianças.",
    images: [{ src: sandalia, alt: "Sandália infantil Grendene" }],
    categories: ["calcados", "infantil"],
    gender: "unissex",
    regular_price: 89.9,
    sale_price: null,
    sizes: ["22", "23", "24", "25", "26", "27"],
    colors: ["Rosa"],
    stock_status: "instock",
    stock_quantity: 40,
    rating: 4.7,
    rating_count: 22,
    featured: false,
    is_new: false,
    best_seller: 65,
    created_at: "2026-07-15",
    attributes: [{ label: "Material", value: "PVC expandido" }],
    size_chart: [{ size: "22", equivalence: "14,5 cm" }],
    reviews: [],
  },
  {
    name: "Mocassim Ferracini Couro Whisky",
    slug: "mocassim-ferracini-couro-whisky",
    sku: "INV-CAL-0106",
    brand: "Ferracini",
    short_description: "Mocassim social em couro legítimo.",
    description: "Construção em couro legítimo com acabamento whisky e costura aparente.",
    images: [{ src: mocassim, alt: "Mocassim Ferracini whisky" }],
    categories: ["calcados", "masculino"],
    gender: "masculino",
    regular_price: 429.9,
    sale_price: 369.9,
    sizes: SIZES_MASC,
    colors: ["Whisky"],
    stock_status: "instock",
    stock_quantity: 7,
    rating: 4.9,
    rating_count: 22,
    featured: true,
    is_new: false,
    best_seller: 84,
    created_at: "2026-03-22",
    attributes: [{ label: "Material", value: "Couro legítimo" }],
    size_chart: CHART_MASC,
    reviews: [],
  },
  {
    name: "Bota Coturno Via Marte",
    slug: "bota-coturno-via-marte",
    sku: "INV-CAL-0111",
    brand: "Via Marte",
    short_description: "Coturno tratorado com acabamento premium.",
    description: "Estilo urbano e resistente para os dias mais frios.",
    images: [{ src: bota, alt: "Bota coturno Via Marte" }],
    categories: ["calcados", "feminino"],
    gender: "feminino",
    regular_price: 349.9,
    sale_price: null,
    sizes: SIZES_FEM,
    colors: ["Preto"],
    stock_status: "instock",
    stock_quantity: 10,
    rating: 4.7,
    rating_count: 12,
    featured: false,
    is_new: true,
    best_seller: 70,
    created_at: "2026-08-11",
    attributes: [{ label: "Solado", value: "Tratorado" }],
    size_chart: CHART_FEM,
    reviews: [],
  }
];

export const MOCK_PRODUCTS: Product[] = seeds.map((seed, index) => ({
  ...seed,
  product_id: 1000 + index,
  price: seed.sale_price ?? seed.regular_price,
}));
