import type { Product } from "./types";

import tenisBranco from "@/assets/p-tenis-branco.jpg";
import tenisPreto from "@/assets/p-tenis-preto.jpg";
import scarpin from "@/assets/p-scarpin.jpg";
import sandalia from "@/assets/p-sandalia.jpg";
import bota from "@/assets/p-bota.jpg";
import mocassim from "@/assets/p-mocassim.jpg";
import bolsaPreta from "@/assets/p-bolsa-preta.jpg";
import bolsaCaramelo from "@/assets/p-bolsa-caramelo.jpg";
import mochila from "@/assets/p-mochila.jpg";
import camiseta from "@/assets/p-camiseta.jpg";
import vestido from "@/assets/p-vestido.jpg";
import jeans from "@/assets/p-jeans.jpg";
import relogio from "@/assets/p-relogio.jpg";
import oculos from "@/assets/p-oculos.jpg";
import cinto from "@/assets/p-cinto.jpg";

const SIZES_FEM = ["34", "35", "36", "37", "38", "39"];
const SIZES_MASC = ["38", "39", "40", "41", "42", "43"];
const SIZES_ROUPA = ["P", "M", "G", "GG"];
const SIZE_UNICO = ["Único"];

const CHART_FEM = [
  { size: "34", equivalence: "22,0 cm" },
  { size: "35", equivalence: "22,8 cm" },
  { size: "36", equivalence: "23,5 cm" },
  { size: "37", equivalence: "24,3 cm" },
  { size: "38", equivalence: "25,0 cm" },
  { size: "39", equivalence: "25,8 cm" },
];

const CHART_MASC = [
  { size: "38", equivalence: "24,8 cm" },
  { size: "39", equivalence: "25,5 cm" },
  { size: "40", equivalence: "26,2 cm" },
  { size: "41", equivalence: "27,0 cm" },
  { size: "42", equivalence: "27,7 cm" },
  { size: "43", equivalence: "28,5 cm" },
];

type Seed = Omit<Product, "price" | "product_id"> & { product_id?: number };

const seeds: Seed[] = [
  {
    name: "Tênis Adidas Runfalcon 3.0",
    slug: "tenis-adidas-runfalcon-3-0",
    sku: "INV-CAL-0101",
    brand: "Adidas",
    short_description: "Tênis esportivo leve com amortecimento para o dia a dia.",
    description:
      "O Runfalcon 3.0 combina cabedal em tecido respirável e entressola macia para quem passa o dia em movimento. Acabamento limpo em branco total, fácil de compor com jeans, alfaiataria leve ou look esportivo.",
    images: [{ src: tenisBranco, alt: "Tênis Adidas Runfalcon branco visto de três quartos" }],
    categories: ["calcados"],
    gender: "unissex",
    regular_price: 449.9,
    sale_price: 399.9,
    sizes: SIZES_MASC,
    colors: ["Branco"],
    stock_status: "instock",
    stock_quantity: 18,
    rating: 4.8,
    rating_count: 46,
    featured: true,
    is_new: true,
    best_seller: 96,
    created_at: "2026-07-28",
    attributes: [
      { label: "Material", value: "Têxtil e sintético" },
      { label: "Solado", value: "EVA com borracha" },
      { label: "Palmilha", value: "Removível acolchoada" },
    ],
    size_chart: CHART_MASC,
    reviews: [
      {
        author: "Rafaela M.",
        rating: 5,
        date: "2026-07-02",
        comment: "Muito confortável e chegou rápido. Comprei pelo WhatsApp e fui bem atendida.",
      },
      {
        author: "Diego S.",
        rating: 5,
        date: "2026-06-18",
        comment: "Numeração fiel, uso para trabalhar em pé o dia inteiro.",
      },
    ],
  },
  {
    name: "Tênis Puma Softride Preto",
    slug: "tenis-puma-softride-preto",
    sku: "INV-CAL-0102",
    brand: "Puma",
    short_description: "Silhueta esportiva all black com pisada macia.",
    description:
      "Versão monocromática do Softride, com espuma de retorno suave e cabedal em malha. Discreto o suficiente para o ambiente de trabalho e confortável para as caminhadas do fim de semana.",
    images: [{ src: tenisPreto, alt: "Tênis Puma Softride preto de perfil" }],
    categories: ["calcados"],
    gender: "masculino",
    regular_price: 379.9,
    sale_price: null,
    sizes: SIZES_MASC,
    colors: ["Preto"],
    stock_status: "instock",
    stock_quantity: 12,
    rating: 4.6,
    rating_count: 31,
    featured: true,
    is_new: false,
    best_seller: 88,
    created_at: "2026-06-11",
    attributes: [
      { label: "Material", value: "Malha respirável" },
      { label: "Solado", value: "Softride" },
    ],
    size_chart: CHART_MASC,
    reviews: [
      {
        author: "Antônio C.",
        rating: 5,
        date: "2026-05-30",
        comment: "Sóbrio e confortável, exatamente o que procurava.",
      },
    ],
  },
  {
    name: "Scarpin Vizzano Bico Fino Nude",
    slug: "scarpin-vizzano-bico-fino-nude",
    sku: "INV-CAL-0103",
    brand: "Vizzano",
    short_description: "Scarpin clássico em verniz, salto fino de 9 cm.",
    description:
      "O scarpin nude alonga a silhueta e resolve do escritório ao casamento. Verniz de brilho uniforme, forro macio e palmilha almofadada para uso prolongado.",
    images: [{ src: scarpin, alt: "Scarpin Vizzano nude de bico fino" }],
    categories: ["calcados"],
    gender: "feminino",
    regular_price: 219.9,
    sale_price: 179.9,
    sizes: SIZES_FEM,
    colors: ["Nude"],
    stock_status: "instock",
    stock_quantity: 22,
    rating: 4.7,
    rating_count: 58,
    featured: true,
    is_new: false,
    best_seller: 94,
    created_at: "2026-05-20",
    attributes: [
      { label: "Altura do salto", value: "9 cm" },
      { label: "Material", value: "Verniz sintético" },
    ],
    size_chart: CHART_FEM,
    reviews: [
      {
        author: "Juliana P.",
        rating: 5,
        date: "2026-06-09",
        comment: "Usei oito horas em um evento e não machucou.",
      },
    ],
  },
  {
    name: "Sandália Moleca Tiras Caramelo",
    slug: "sandalia-moleca-tiras-caramelo",
    sku: "INV-CAL-0104",
    brand: "Moleca",
    short_description: "Rasteira de tiras finas com fecho no tornozelo.",
    description:
      "Rasteira leve de tiras em caramelo, com fivela metálica e palmilha anatômica. A peça mais versátil do verão: combina com vestido, short e alfaiataria clara.",
    images: [{ src: sandalia, alt: "Sandália rasteira Moleca caramelo com tiras" }],
    categories: ["calcados"],
    gender: "feminino",
    regular_price: 149.9,
    sale_price: 119.9,
    sizes: SIZES_FEM,
    colors: ["Caramelo"],
    stock_status: "instock",
    stock_quantity: 30,
    rating: 4.5,
    rating_count: 24,
    featured: false,
    is_new: true,
    best_seller: 72,
    created_at: "2026-08-01",
    attributes: [
      { label: "Fechamento", value: "Fivela" },
      { label: "Palmilha", value: "Anatômica" },
    ],
    size_chart: CHART_FEM,
    reviews: [],
  },
  {
    name: "Bota Ramarim Cano Curto",
    slug: "bota-ramarim-cano-curto",
    sku: "INV-CAL-0105",
    brand: "Ramarim",
    short_description: "Ankle boot em couro sintético com salto bloco.",
    description:
      "Cano curto, zíper lateral e salto bloco de 4 cm: a bota que atravessa o ano. Caimento estruturado que valoriza calça reta e vestido midi.",
    images: [{ src: bota, alt: "Ankle boot Ramarim marrom de cano curto" }],
    categories: ["calcados"],
    gender: "feminino",
    regular_price: 299.9,
    sale_price: null,
    sizes: SIZES_FEM,
    colors: ["Marrom"],
    stock_status: "instock",
    stock_quantity: 9,
    rating: 4.4,
    rating_count: 17,
    featured: false,
    is_new: false,
    best_seller: 61,
    created_at: "2026-04-14",
    attributes: [
      { label: "Altura do salto", value: "4 cm" },
      { label: "Fechamento", value: "Zíper lateral" },
    ],
    size_chart: CHART_FEM,
    reviews: [],
  },
  {
    name: "Mocassim Ferracini Couro Whisky",
    slug: "mocassim-ferracini-couro-whisky",
    sku: "INV-CAL-0106",
    brand: "Ferracini",
    short_description: "Mocassim social em couro legítimo, solado costurado.",
    description:
      "Construção em couro legítimo com acabamento whisky e costura aparente. Peça de base para o guarda-roupa masculino, do trabalho ao casamento.",
    images: [{ src: mocassim, alt: "Mocassim masculino em couro whisky" }],
    categories: ["calcados"],
    gender: "masculino",
    regular_price: 429.9,
    sale_price: 369.9,
    sizes: SIZES_MASC,
    colors: ["Whisky"],
    stock_status: "instock",
    stock_quantity: 7,
    rating: 4.9,
    rating_count: 22,
    featured: true,
    is_new: false,
    best_seller: 84,
    created_at: "2026-03-22",
    attributes: [
      { label: "Material", value: "Couro legítimo" },
      { label: "Solado", value: "Costurado" },
    ],
    size_chart: CHART_MASC,
    reviews: [
      {
        author: "Marcos V.",
        rating: 5,
        date: "2026-04-27",
        comment: "Couro de verdade, acabamento excelente.",
      },
    ],
  },
  {
    name: "Tênis Olympikus Corre 3",
    slug: "tenis-olympikus-corre-3",
    sku: "INV-CAL-0107",
    brand: "Olympikus",
    short_description: "Tênis de corrida nacional, leve e respirável.",
    description:
      "Desenvolvido para rodagem diária, com entressola responsiva e cabedal em knit. Excelente relação entre conforto e preço para quem começa a correr.",
    images: [{ src: tenisBranco, alt: "Tênis de corrida Olympikus branco" }],
    categories: ["calcados"],
    gender: "unissex",
    regular_price: 329.9,
    sale_price: 279.9,
    sizes: SIZES_MASC,
    colors: ["Branco"],
    stock_status: "instock",
    stock_quantity: 14,
    rating: 4.5,
    rating_count: 39,
    featured: false,
    is_new: false,
    best_seller: 78,
    created_at: "2026-02-19",
    attributes: [{ label: "Indicação", value: "Corrida e caminhada" }],
    size_chart: CHART_MASC,
    reviews: [],
  },
  {
    name: "Sapatilha Beira Rio Bico Redondo",
    slug: "sapatilha-beira-rio-bico-redondo",
    sku: "INV-CAL-0108",
    brand: "Beira Rio",
    short_description: "Sapatilha confortável para uso diário.",
    description:
      "Modelo fechado de bico redondo, com elástico discreto no cós e palmilha macia. Alternativa prática ao salto sem perder a elegância.",
    images: [{ src: scarpin, alt: "Sapatilha feminina Beira Rio nude" }],
    categories: ["calcados"],
    gender: "feminino",
    regular_price: 139.9,
    sale_price: null,
    sizes: SIZES_FEM,
    colors: ["Nude"],
    stock_status: "outofstock",
    stock_quantity: 0,
    rating: 4.3,
    rating_count: 12,
    featured: false,
    is_new: false,
    best_seller: 55,
    created_at: "2026-01-30",
    attributes: [{ label: "Material", value: "Sintético" }],
    size_chart: CHART_FEM,
    reviews: [],
  },
  {
    name: "Bolsa Chenson Estruturada Preta",
    slug: "bolsa-chenson-estruturada-preta",
    sku: "INV-BOL-0201",
    brand: "Chenson",
    short_description: "Bolsa tote estruturada com alças de mão.",
    description:
      "Volume amplo com estrutura firme, compartimento interno com zíper e forro reforçado. Cabe notebook de 14 polegadas — a bolsa de trabalho definitiva.",
    images: [{ src: bolsaPreta, alt: "Bolsa tote preta estruturada Chenson" }],
    categories: ["bolsas"],
    gender: "feminino",
    regular_price: 289.9,
    sale_price: 239.9,
    sizes: SIZE_UNICO,
    colors: ["Preto"],
    stock_status: "instock",
    stock_quantity: 11,
    rating: 4.8,
    rating_count: 34,
    featured: true,
    is_new: false,
    best_seller: 90,
    created_at: "2026-06-25",
    attributes: [
      { label: "Medidas", value: "32 x 30 x 12 cm" },
      { label: "Alças", value: "Mão e transversal removível" },
    ],
    reviews: [
      {
        author: "Camila R.",
        rating: 5,
        date: "2026-07-10",
        comment: "Bolsa firme, não deforma. Uso todos os dias no trabalho.",
      },
    ],
  },
  {
    name: "Bolsa Petite Jolie Shopper Caramelo",
    slug: "bolsa-petite-jolie-shopper-caramelo",
    sku: "INV-BOL-0202",
    brand: "Petite Jolie",
    short_description: "Shopper ampla em caramelo com alças longas.",
    description:
      "Modelo shopper de linhas limpas em caramelo, alças longas para uso no ombro e bolso interno. Leve e resistente ao uso diário.",
    images: [{ src: bolsaCaramelo, alt: "Bolsa shopper caramelo Petite Jolie" }],
    categories: ["bolsas"],
    gender: "feminino",
    regular_price: 259.9,
    sale_price: null,
    sizes: SIZE_UNICO,
    colors: ["Caramelo"],
    stock_status: "instock",
    stock_quantity: 16,
    rating: 4.6,
    rating_count: 21,
    featured: true,
    is_new: true,
    best_seller: 80,
    created_at: "2026-08-05",
    attributes: [{ label: "Medidas", value: "35 x 33 x 11 cm" }],
    reviews: [],
  },
  {
    name: "Mochila Puma Urbana Preta",
    slug: "mochila-puma-urbana-preta",
    sku: "INV-BOL-0203",
    brand: "Puma",
    short_description: "Mochila resistente com compartimento para notebook.",
    description:
      "Mochila de uso urbano com bolso frontal em zíper, alças acolchoadas e divisória interna protegida para notebook. Tecido de alta resistência.",
    images: [{ src: mochila, alt: "Mochila urbana preta Puma" }],
    categories: ["bolsas"],
    gender: "unissex",
    regular_price: 249.9,
    sale_price: 199.9,
    sizes: SIZE_UNICO,
    colors: ["Preto"],
    stock_status: "instock",
    stock_quantity: 20,
    rating: 4.7,
    rating_count: 27,
    featured: false,
    is_new: false,
    best_seller: 82,
    created_at: "2026-05-04",
    attributes: [{ label: "Capacidade", value: "22 litros" }],
    reviews: [],
  },
  {
    name: "Bolsa Dumond Crossbody Preta",
    slug: "bolsa-dumond-crossbody-preta",
    sku: "INV-BOL-0204",
    brand: "Dumond",
    short_description: "Bolsa transversal compacta para o dia a dia.",
    description:
      "Formato compacto com alça transversal ajustável e ferragem dourada discreta. Ideal para levar o essencial com elegância.",
    images: [{ src: bolsaPreta, alt: "Bolsa crossbody preta Dumond" }],
    categories: ["bolsas"],
    gender: "feminino",
    regular_price: 219.9,
    sale_price: null,
    sizes: SIZE_UNICO,
    colors: ["Preto"],
    stock_status: "instock",
    stock_quantity: 13,
    rating: 4.4,
    rating_count: 15,
    featured: false,
    is_new: false,
    best_seller: 64,
    created_at: "2026-03-09",
    attributes: [{ label: "Medidas", value: "22 x 16 x 7 cm" }],
    reviews: [],
  },
  {
    name: "Camiseta Hering Básica Preta",
    slug: "camiseta-hering-basica-preta",
    sku: "INV-ROU-0301",
    brand: "Hering",
    short_description: "Camiseta de algodão com modelagem reta.",
    description:
      "Algodão penteado de toque macio, gola trabalhada que não perde a forma e modelagem reta. A base de qualquer look masculino.",
    images: [{ src: camiseta, alt: "Camiseta básica preta Hering dobrada" }],
    categories: ["roupas"],
    gender: "masculino",
    regular_price: 89.9,
    sale_price: 69.9,
    sizes: SIZES_ROUPA,
    colors: ["Preto"],
    stock_status: "instock",
    stock_quantity: 40,
    rating: 4.7,
    rating_count: 62,
    featured: true,
    is_new: false,
    best_seller: 92,
    created_at: "2026-06-02",
    attributes: [
      { label: "Composição", value: "100% algodão" },
      { label: "Modelagem", value: "Reta" },
    ],
    reviews: [
      {
        author: "Pedro L.",
        rating: 5,
        date: "2026-06-21",
        comment: "Tecido bom, não desbotou depois de várias lavagens.",
      },
    ],
  },
  {
    name: "Vestido Colcci Midi Preto",
    slug: "vestido-colcci-midi-preto",
    sku: "INV-ROU-0302",
    brand: "Colcci",
    short_description: "Vestido midi transpassado com manga curta.",
    description:
      "Corte transpassado que marca a cintura, tecido de caimento fluido e comprimento midi. Resolve jantar, formatura e casamento com um scarpin.",
    images: [{ src: vestido, alt: "Vestido midi preto Colcci" }],
    categories: ["roupas"],
    gender: "feminino",
    regular_price: 399.9,
    sale_price: 329.9,
    sizes: SIZES_ROUPA,
    colors: ["Preto"],
    stock_status: "instock",
    stock_quantity: 8,
    rating: 4.9,
    rating_count: 19,
    featured: true,
    is_new: true,
    best_seller: 86,
    created_at: "2026-08-08",
    attributes: [
      { label: "Composição", value: "Viscose com elastano" },
      { label: "Comprimento", value: "Midi" },
    ],
    reviews: [
      {
        author: "Larissa F.",
        rating: 5,
        date: "2026-08-01",
        comment: "Caimento maravilhoso, recebi muitos elogios.",
      },
    ],
  },
  {
    name: "Calça Jeans Colcci Skinny",
    slug: "calca-jeans-colcci-skinny",
    sku: "INV-ROU-0303",
    brand: "Colcci",
    short_description: "Jeans skinny com elastano e cintura alta.",
    description:
      "Lavagem média uniforme, cintura alta e elastano que acompanha o movimento sem alargar. Modelagem skinny que valoriza a silhueta.",
    images: [{ src: jeans, alt: "Calça jeans skinny azul dobrada" }],
    categories: ["roupas"],
    gender: "feminino",
    regular_price: 299.9,
    sale_price: null,
    sizes: ["36", "38", "40", "42", "44"],
    colors: ["Azul"],
    stock_status: "instock",
    stock_quantity: 15,
    rating: 4.5,
    rating_count: 28,
    featured: false,
    is_new: false,
    best_seller: 74,
    created_at: "2026-04-01",
    attributes: [{ label: "Composição", value: "Algodão com elastano" }],
    reviews: [],
  },
  {
    name: "Camisa Social Aramis Slim Branca",
    slug: "camisa-social-aramis-slim-branca",
    sku: "INV-ROU-0304",
    brand: "Aramis",
    short_description: "Camisa social de algodão com modelagem slim.",
    description:
      "Tecido de fio egípcio, colarinho estruturado e modelagem slim. Peça de rigor para o guarda-roupa social masculino.",
    images: [{ src: camiseta, alt: "Camisa social branca dobrada" }],
    categories: ["roupas"],
    gender: "masculino",
    regular_price: 259.9,
    sale_price: 219.9,
    sizes: SIZES_ROUPA,
    colors: ["Branco"],
    stock_status: "instock",
    stock_quantity: 10,
    rating: 4.6,
    rating_count: 14,
    featured: false,
    is_new: true,
    best_seller: 68,
    created_at: "2026-07-19",
    attributes: [{ label: "Composição", value: "100% algodão" }],
    reviews: [],
  },
  {
    name: "Bermuda Sarja Masculina Preta",
    slug: "bermuda-sarja-masculina-preta",
    sku: "INV-ROU-0305",
    brand: "Hering",
    short_description: "Bermuda de sarja com elastano e bolsos laterais.",
    description:
      "Sarja de gramatura média com toque macio e leve elasticidade. Cinco bolsos e acabamento reforçado nas costuras.",
    images: [{ src: jeans, alt: "Bermuda de sarja preta dobrada" }],
    categories: ["roupas"],
    gender: "masculino",
    regular_price: 159.9,
    sale_price: 129.9,
    sizes: ["38", "40", "42", "44", "46"],
    colors: ["Preto"],
    stock_status: "instock",
    stock_quantity: 18,
    rating: 4.3,
    rating_count: 11,
    featured: false,
    is_new: false,
    best_seller: 58,
    created_at: "2026-02-08",
    attributes: [{ label: "Composição", value: "Sarja com elastano" }],
    reviews: [],
  },
  {
    name: "Relógio Mondaine Dourado",
    slug: "relogio-mondaine-dourado",
    sku: "INV-ACE-0401",
    brand: "Mondaine",
    short_description: "Relógio analógico dourado com pulseira em aço.",
    description:
      "Caixa de 38 mm em aço dourado, mostrador champanhe e resistência à água. Acessório que fecha o look com sofisticação sem exagero.",
    images: [{ src: relogio, alt: "Relógio analógico dourado com pulseira de aço" }],
    categories: ["acessorios"],
    gender: "unissex",
    regular_price: 379.9,
    sale_price: 319.9,
    sizes: SIZE_UNICO,
    colors: ["Dourado"],
    stock_status: "instock",
    stock_quantity: 6,
    rating: 4.8,
    rating_count: 23,
    featured: true,
    is_new: false,
    best_seller: 89,
    created_at: "2026-05-16",
    attributes: [
      { label: "Caixa", value: "38 mm" },
      { label: "Resistência", value: "3 ATM" },
      { label: "Garantia", value: "12 meses" },
    ],
    reviews: [
      {
        author: "Bruna T.",
        rating: 5,
        date: "2026-06-01",
        comment: "Mais bonito do que nas fotos, ótimo acabamento.",
      },
    ],
  },
  {
    name: "Óculos de Sol Mormaii Aviador",
    slug: "oculos-de-sol-mormaii-aviador",
    sku: "INV-ACE-0402",
    brand: "Mormaii",
    short_description: "Aviador com lentes polarizadas e proteção UV400.",
    description:
      "Armação metálica leve, lentes polarizadas com proteção UV400 e hastes em acetato. Vem com case e flanela.",
    images: [{ src: oculos, alt: "Óculos de sol aviador preto e dourado" }],
    categories: ["acessorios"],
    gender: "unissex",
    regular_price: 299.9,
    sale_price: 249.9,
    sizes: SIZE_UNICO,
    colors: ["Preto"],
    stock_status: "instock",
    stock_quantity: 12,
    rating: 4.7,
    rating_count: 30,
    featured: true,
    is_new: true,
    best_seller: 85,
    created_at: "2026-07-31",
    attributes: [
      { label: "Lente", value: "Polarizada UV400" },
      { label: "Acompanha", value: "Case e flanela" },
    ],
    reviews: [],
  },
  {
    name: "Cinto de Couro Masculino Marrom",
    slug: "cinto-de-couro-masculino-marrom",
    sku: "INV-ACE-0403",
    brand: "Ferracini",
    short_description: "Cinto em couro legítimo com fivela discreta.",
    description:
      "Couro legítimo de 3,5 cm de largura, costura reforçada e fivela em metal escovado. Combina com mocassim e sapato social.",
    images: [{ src: cinto, alt: "Cinto de couro marrom enrolado" }],
    categories: ["acessorios"],
    gender: "masculino",
    regular_price: 139.9,
    sale_price: null,
    sizes: ["90", "95", "100", "105"],
    colors: ["Marrom"],
    stock_status: "instock",
    stock_quantity: 25,
    rating: 4.5,
    rating_count: 16,
    featured: false,
    is_new: false,
    best_seller: 62,
    created_at: "2026-01-18",
    attributes: [{ label: "Material", value: "Couro legítimo" }],
    reviews: [],
  },
  {
    name: "Carteira Feminina em Couro Caramelo",
    slug: "carteira-feminina-em-couro-caramelo",
    sku: "INV-ACE-0404",
    brand: "Chenson",
    short_description: "Carteira com porta-cartões e compartimento para notas.",
    description:
      "Couro sintético de toque macio, oito espaços para cartões, porta-moedas com zíper e acabamento em costura contrastante.",
    images: [{ src: bolsaCaramelo, alt: "Carteira feminina em couro caramelo" }],
    categories: ["acessorios"],
    gender: "feminino",
    regular_price: 119.9,
    sale_price: 89.9,
    sizes: SIZE_UNICO,
    colors: ["Caramelo"],
    stock_status: "instock",
    stock_quantity: 28,
    rating: 4.4,
    rating_count: 13,
    featured: false,
    is_new: false,
    best_seller: 57,
    created_at: "2026-03-27",
    attributes: [{ label: "Cartões", value: "8 espaços" }],
    reviews: [],
  },
  {
    name: "Tênis Mizuno Wave Feminino",
    slug: "tenis-mizuno-wave-feminino",
    sku: "INV-CAL-0109",
    brand: "Mizuno",
    short_description: "Tênis de performance com tecnologia de amortecimento.",
    description:
      "Placa Wave para distribuição do impacto, cabedal em mesh e ajuste preciso no calcanhar. Indicado para treinos de rua e academia.",
    images: [{ src: tenisBranco, alt: "Tênis Mizuno Wave feminino branco" }],
    categories: ["calcados"],
    gender: "feminino",
    regular_price: 599.9,
    sale_price: 499.9,
    sizes: SIZES_FEM,
    colors: ["Branco"],
    stock_status: "instock",
    stock_quantity: 5,
    rating: 4.9,
    rating_count: 20,
    featured: true,
    is_new: true,
    best_seller: 91,
    created_at: "2026-08-10",
    attributes: [{ label: "Indicação", value: "Treino e corrida" }],
    size_chart: CHART_FEM,
    reviews: [],
  },
];

export const MOCK_PRODUCTS: Product[] = seeds.map((seed, index) => ({
  ...seed,
  product_id: 1000 + index,
  price: seed.sale_price ?? seed.regular_price,
}));
